"""
"""

alias(
    name = "lua",
    # FIXME: select according to target lua version
    actual = "@remote_lua53_repository//:lua"
)

alias(
    name = "luac",
    # FIXME: select according to target lua version
    actual = "@remote_lua53_repository//:luac"
)
